spring.application.name=mo_gaia_project_be

spring.datasource.url=jdbc:postgresql://localhost:5432/gaia
spring.datasource.username=gaia
spring.datasource.password=gaia

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
